ReportViewerForMvc.Example/Controllers/ExamplesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Reporting.WebForms;
using System.Web.UI.WebControls;
using System.Data;
using System.Data.SqlClient;
using ReportViewerForMvc.Example.Reports;

namespace ReportViewerForMvc.Example.Controllers
{
    public class ExamplesController : Controller
    {
        private dsLocalReport tds = new dsLocalReport();

        //
        // GET: /Example/
        public ActionResult AnonymousExample()
        {
            return View();
        }

        /// <summary>
        /// Creates a ReportViewer control and stores it on the ViewBag
        /// </summary>
        /// <returns></returns>
        public ActionResult ServerReportExample()
        {
            ReportViewer reportViewer = new ReportViewer();
            reportViewer.ProcessingMode = ProcessingMode.Remote;
            reportViewer.SizeToReportContent = true;
            reportViewer.Width = Unit.Percentage(100);
            reportViewer.Height = Unit.Percentage(100);

            reportViewer.ServerReport.ReportPath = "/AdventureWorks 2012/Sales_by_Region";
            reportViewer.ServerReport.ReportServerUrl = new Uri("http://localhost/ReportServer/");
            reportViewer.ServerReport.SetParameters(GetParametersServer());

            ViewBag.ReportViewer = reportViewer;

            return View();
        }

        /// <summary>
        /// Creates a ReportViewer control and stores it on the ViewBag
        /// </summary>
        /// <returns></returns>
        public ActionResult LocalReportExample()
        {
            SetLocalReport();

            return View();
        }

        private void SetLocalReport()
        {
            ReportViewer reportViewer = new ReportViewer();
            reportViewer.ProcessingMode = ProcessingMode.Local;
            reportViewer.SizeToReportContent = true;
            reportViewer.Width = Unit.Percentage(100);
            reportViewer.Height = Unit.Percentage(100);

            FillDataSet();
            reportViewer.LocalReport.ReportPath = Request.MapPath(Request.ApplicationPath) + @"Reports\LocalReportExample.rdlc";
            reportViewer.LocalReport.DataSources.Add(new ReportDataSource("dsLocalReport", tds.Tables[0]));
            reportViewer.LocalReport.SetParameters(GetParametersLocal());

            ViewBag.ReportViewer = reportViewer;
        }

        private void FillDataSet()
        {
            string connectionString = GetConnectionString();

            using (SqlConnection sqlConnection = new SqlConnection(connectionString))
            {
                string queryString = GetQueryString();

                SqlDataAdapter sqlDataAapter = new SqlDataAdapter(queryString, sqlConnection);

                sqlDataAapter.Fill(tds, tds.DataTable1.TableName);
            }
        }

        private string GetConnectionString()
        {
            return "Data Source=localhost;Initial Catalog=AdventureWorks2012;Integrated Security=True";
        }

        private string GetQueryString()
        {
            return "SELECT d.name as Dept, s.Name as Shift, e.BusinessEntityID as EmployeeID"
                + " FROM (HumanResources.Department d INNER JOIN HumanResources.EmployeeDepartmentHistory e ON d.DepartmentID = e.DepartmentID)"
                + " INNER JOIN HumanResources.Shift s ON e.ShiftID = s.ShiftID";
        }

        private ReportParameter[] GetParametersLocal()
        {
            ReportParameter p1 = new ReportParameter("ReportTitle", "Local Report Example");
            return new ReportParameter[] { p1 };
        }

        private ReportParameter[] GetParametersServer()
        {
            ReportParameter p1 = new ReportParameter("ShowBingMaps", "Visible");
            ReportParameter p2 = new ReportParameter("ShowAll", "True");
            return new ReportParameter[] { p1, p2 };
        }

    }
}

ReportViewerForMvc.Example/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ReportViewerForMvc.Example.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

ReportViewerForMvc.Example/Views/Examples/AnonymousExample.cshtml
@using ReportViewerForMvc;
@using System.Web.UI.WebControls;

@{
    ViewBag.Title = "Anonymous Example";
}

<h2>AnonymousExample</h2>

@{
    List<object> dataList = new List<object>();
    var data = new
    {
        Dept = "Document Control",
        Shift = "Day",
        EmployeeID = "1"
    };
    dataList.Add(data);
}

@Html.ReportViewer(
    new
    {
        ProcessingMode = 0, //ProcessingMode.Local
        SizeToReportContent = true,
        Width = Unit.Percentage(100),
        Height = Unit.Percentage(100)
    },
    new
    {
        ReportPath = Request.MapPath(Request.ApplicationPath) + @"Reports\LocalReportExample.rdlc"
    },
    new
    {
        ReportTitle = "Local Report Example"
    },
    new
    {
        Name = "dsLocalReport",
        Value = dataList
    },
    null)

ReportViewerForMvc.Example/Views/Examples/LocalReportExample.cshtml
@using ReportViewerForMvc;

@{
    ViewBag.Title = "LocalReportExample";
}


<h2>Local report example</h2>

@Html.ReportViewer(ViewBag.ReportViewer as Microsoft.Reporting.WebForms.ReportViewer)

ReportViewerForMvc.Example/Views/Examples/ServerReportExample.cshtml
@using ReportViewerForMvc;

@{
    ViewBag.Title = "Control Example";
}

<h2>Server report example</h2>

@Html.ReportViewer(
    ViewBag.ReportViewer as Microsoft.Reporting.WebForms.ReportViewer, 
    new { scrolling = "no" })

ReportViewerForMvc.Example/Views/Home/Index.cshtml
@{
    ViewBag.Title = "ReportViewerForMvc Helper";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

ReportViewerForMvc.Example/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ReportViewerForMvc - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ReportViewerForMvc", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Anonymous Example", "AnonymousExample", "Examples")</li>
                    <li>@Html.ActionLink("Server Report Example", "ServerReportExample", "Examples")</li>
                    <li>@Html.ActionLink("Local Report Example", "LocalReportExample", "Examples")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>